### ISSUE TITLE
[Bug]  [Firefox nightly (67)] Articles in the feed item list cannot be opened/clicked on anymore

### ISSUE THREAD

**Issue by Judy85** [dauphine-dev/drop-feeds#101] opened 2019-02-06 09:48 UTC
Hi Dauphine-dev,

Maybe a bit in advance, but I wanted to make you aware now of the following. In the current Firefox nightly (67) I found that the articles in the feed item list cannot be opened/clicked on anymore. For the moment using Firefox beta (version 66) without problem. Maybe something to do with XBL removal?

![image](https://user-images.githubusercontent.com/33347388/52332857-16a63700-29fc-11e9-9656-6dc3a503faf8.png)

#### System: 
 * Operating System:  Windows 10 - 1803
 * Firefox: 67 (current nightly)

#### Steps to reproduce:
Click feed - feed item list loads

#### What should happen:
feed item list populated and articles can be opened by clicking

#### What actually happened:
feed item list populated, but articles cannot be clicked on
(feed item list loaded maybe with Firefox unknown problem popup)

Cheers!

**Comment by dauphine-dev** [comment] 2019-02-06 10:31
@Judy85 
Thank you for the bug report in advance (sooner is better).
But I have just checked with the Firefox nightly and I haven't this issue.

But may be you have the option "Render selected item in the sidebar" (1) activated, you render panel (2) is set to the minimum size at the bottom of the side bar, then move (3) the splitter bar to the top.

Please confirm that it is ok for you then I will close the issue, if not tell me more or post a screen shot to help me  o understood what is happening.
![image](https://user-images.githubusercontent.com/36274213/52335192-098c4680-2a02-11e9-9f7e-61cc519777ab.png)

**Comment by Judy85** [comment] 2019-02-06 11:41
@dauphine-dev 

Thanks for looking into this. Hereby my steps.

![image](https://user-images.githubusercontent.com/33347388/52338782-a0113580-2a0b-11e9-93d6-b2807f3d7a4e.png)

1. Created new profile;
2. Installed dropfeeds without further configuration actions;
3. Clicked dropfeeds releases feed;
4. I cannot click any of the releases articles shown.

**Comment by dauphine-dev** [comment] 2019-02-06 12:58
Weird,
I have done exactly like you, but it works here:
![image](https://user-images.githubusercontent.com/36274213/52341465-eb7b1200-2a12-11e9-8aa6-a2a30dd6aeb2.png)

* Created new profile;
* Installed dropfeeds without further configuration actions;
* Clicked dropfeeds releases feed;
* I can click on a release article and  it is displayed in the bottom panel.

Then I afraid I will need your help to debug that:
 - [Display the debug console](https://github.com/dauphine-dev/drop-feeds/wiki/How-to-display-the-debug-console-%3F)
 - Click on a feed
 - Click on an article
 - Copy and paste any messages in this thread

Thank you.

**Comment by dauphine-dev** [comment] 2019-02-06 14:51
Ooops, sorry, my bad, I wasn't runing "Nightly", but "Developer Edition", now I reproduce.
Thank you for your time

**Comment by Judy85** [comment] 2019-02-06 15:03
Happy to help! Thank you too!

**Comment by dauphine-dev** [comment] 2019-02-06 15:29
It is because there is an issue with API `history.getVisits`, I have done a workaround by settings by default all articles to non visited status.
This workaround is available in [Drop Feed 0.9.5rc1](https://github.com/dauphine-dev/drop-feeds/releases)

**Closed by dauphine-dev** 2019-02-06 15:29 UTC
Labels: bug

**Comment by Judy85** [comment] 2019-02-06 18:16
yay, I can click and open the articles now. Hopefully the API issue will be fixed soonish, bit annoying to see read articles turn unread again when the feed is clicked again. Thanks!
