### ISSUE TITLE
feeds from feedburner.com does not work

### ISSUE THREAD

**Issue by readyblue** [dauphine-dev/drop-feeds#56] opened 2018-09-11 14:58 UTC
hi,
the feeds from :

https://feeds.feedburner.com

does not work. Drop Feeds detect that there are feeds, but it is unable to add them anyhow.
Can you please check what can be the problem since the FeedBurner is used on many webs for RSS, it is not a single web with single feed.
Like for instance:
https://feeds.feedburner.com/Torrentfreak
or
https://feeds.feedburner.com/TheHackersNews

Thanks

**Comment by thieleke** [comment] 2018-09-11 15:59
@readyblue - for the Hacker News site, you need to use the feed URL not the Feedburner page.  So the correct URL (from the "View Feed XML" link is): https://feeds.feedburner.com/TheHackersNews?format=xml

Torrentfreak seems to be a Drop Feeds bug, though:

```
TypeError: "attList is null"
_disableAttributes  js/tools/feedParser.js:652:1
_applySecurityFilters  js/tools/feedParser.js:613:12
_getDescription  js/tools/feedParser.js:574:19
```

**Comment by dauphine-dev** [comment] 2018-09-11 15:59
Hi thank you for your issue report.

I can reproduce the issue for
 - https://feeds.feedburner.com/Torrentfreak
but not for
 - https://feeds.feedburner.com/TheHackersNews
 - https://www.wired.com/feed/rss

any way for Torrentfreak feed, it is a bug in security attributes filters feature, it will be fix soon, I hope it will be fix the two other for you.

**Comment by dauphine-dev** [comment] 2018-09-11 16:17
It is fixed in 0.8.5.
To update to 0.8.5, you need to run Firefox 46.0.1 or above

**Closed by dauphine-dev** 2018-09-11 16:17 UTC

**Comment by readyblue** [comment] 2018-09-12 00:10
Hi, thanks for such an express care.
Forgive me my noob question, but how can edit feed from:
https://feeds.feedburner.com/TheHackersNews
to
https://feeds.feedburner.com/TheHackersNews?format=xml
as suggested earlier? where is that "View Feed XML"?

All feeds before, I have done something like this:
1. load the web page
2. press the "Go to subscription page" button from Drop Feeds panel
3. press the "Go to subscription page" on the navigation bar
4. press the "Subscribe with Drop Feed" on the navigation bar
5. than on the new popup pressing the "Subscribe Now"

Is there another way to change the address like it was suggested before?

The trouble is that the **"Subscribe with Drop Feed" is grayed-out** so it is not possible to add the feed.
Thanks


Yes, I have Firefox 60.2esr and latest update to 0.8.5a

**Comment by readyblue** [comment] 2018-09-12 08:48
@dauphine-dev Thank You very much!
I have manage to change the address as mentioned earlier, unfortunately there is still error:


Name: | The Hacker News
-- | --
Url: | https://feeds.feedburner.com/TheHackersNews?format=xml
Error: | unknown error

No luck with TorrentFreek either:


Name: | TorrentFreak
-- | --
Url: | http://feeds.feedburner.com/Torrentfreak
Error: | unknown error

Cannot figure out what possibly I do wrong, still thanks for all your help.

**Comment by dauphine-dev** [comment] 2018-09-12 09:44
Here theses feeds work well (but may be we have different settings).

Can you :
 - open the Firefox console (ctrl+shift+k)
 - clear the console (click on the trash can on the upper left)
 - open the feed
- and look in the console if you get a message
- copy and paste messages here

**Comment by readyblue** [comment] 2018-09-12 11:49
@dauphine-dev Thanks, I have done that and no output in to console window,
only when I clicked on the URL link when error message was displayed (as pasted earlier), than
the console print following line:

`Use of xml:base attribute is deprecated and will be removed soon. Please remove any use of it.`

This is the same for both TorrentFreak and HackersNews feeds.

**Comment by dauphine-dev** [comment] 2018-09-12 12:01
"Use of xml:base attribute is deprecated and will be removed soon. Please remove any use of it." is not related to your issue (it is warning about old way to encode feed).

Drop Feed shows "unknown error" when some thing went wrong during feed xml file downloading, and  Firefox has raise an error, but the error is empty then the error is unknown. Often it happens when some thing is wrong in security layer of the network connections, like an invalid https certificate.
On my side it works then I don't think that is an invalid https certificate. But your issue seems to be related to a network issue during the feed xml file downloading.

**Comment by dauphine-dev** [comment] 2018-09-12 12:06
May be it can be an other extension that tries to clean network exchange or some thing like that.
You can disable all other extensions, and if it works then enable other extension one by one and see what is the one.

Long time ago I had an issue with "noscript" but I don't remember what it was...

**Comment by readyblue** [comment] 2018-09-12 14:04
@dauphine-dev 
I have tried to disable all plugins, extentions and add-ons but Drop Feed, but the issue persist. I have tried even restart the firefox with all plugins, extentions and add-ons disabled and tried again, but same result. Do not have "noscript" installed.

If there is anything else I can try, just let me know and I will try it.

I am still grateful for Drop Feed as it is. It saved me on after-Sage era.

**Comment by dauphine-dev** [comment] 2018-09-12 14:12
For now I have no more ideas...

One question when you click on links belows
 - https://feeds.feedburner.com/TheHackersNews?format=xml
 - http://feeds.feedburner.com/Torrentfreak
Do you get the Firefox feed view ?

And if you have wget installed can you run 
 - wget "https://feeds.feedburner.com/TheHackersNews?format=xml"
and 
 - wget "http://feeds.feedburner.com/Torrentfreak"

and open download files in a text editor and see if you get a feed xml file well formed ?

In fact it was 2 questions

**Comment by readyblue** [comment] 2018-09-12 14:39
@dauphine-dev 
to your 1st question: Yes, for both.
to your 2nd question: Yes, I have check it with "xmlwf" and it is well-formed, both.

**Comment by dauphine-dev** [comment] 2018-09-12 14:42
@readyblue 
Ok then it is totally weird, sorry but now I have no more ideas :-(

**Comment by readyblue** [comment] 2018-09-12 14:43
@dauphine-dev no problem, thanks anyway.

**Comment by dauphine-dev** [comment] 2018-09-12 16:43
I have just a new idea,.

Try to increase "Timeout" in options "Update checker" tab from 60 to 600 and test.

After that set it to 60 again if not then you will wait for a while before all feeds are finished to check if one is not responding...

**Comment by readyblue** [comment] 2018-09-12 22:31
Found that option and I change it. After that I have checked the feeds, still the same error. After that I have hit the "Check Feeds" refresh button, still the same error, even after changing the value back to 60.

**Comment by dauphine-dev** [comment] 2018-09-13 09:01
Ok,
the last thing to test after that I will really have no more ideas...

Test Drop Feeds in a fresh Firefox profile.
To do that :
 - Close all firefox windows (of any version, any kind, if you have many...)
 - Run: firefox -P
 - Click on "Create Profile" button
 - On the popup, click on the "Next" button
 - On the new screen type a profile name like "test" or what ever you want, and click on the "Finish" button
 - Check that the new profile is selected and click on "Start Firefox" button (may be uncheck "Use the selected profile without asking at statup" (as you want))
 - Then Firefox starts with new one fresh profile
 
Then install Drop Feeds and check if TheHackersNews, and Torrentfreak feeds work.

If yes then it means some is wrong in your usual user profile, may be a value in about:config
If no then it means, I really have no more ideas... and it is really totally weird...

**Comment by readyblue** [comment] 2018-09-13 09:47
@dauphine-dev 
I have tried it, and now it is working. Thanks for all your effort. And as for me, well, I may start to migrate all the bookmarks and stuff to new profile. Thanks again.

**Comment by dauphine-dev** [comment] 2018-09-13 09:50
You are welcome :-)
