### ISSUE TITLE
UI is inactive

### ISSUE THREAD

**Issue by ChrisBertrandDotNet** [dauphine-dev/drop-feeds#57] opened 2018-09-15 10:04 UTC
Hi!

When I try to add the main RSS of the following page, the window does not list the folders and the buttons do not do anything (even "Cancel").

https://blogs.msdn.microsoft.com/visualstudio/

The problematic window:
![inactive](https://user-images.githubusercontent.com/33118130/45585082-dc1def80-b8de-11e8-8f18-202389372074.png)

Context:
FireFox 62.0
Drop Feeds 0.8.5b
Both Windows 7 and 10 (1803)
Other extensions: Adblock Plus and NoScript.

**Comment by ChrisBertrandDotNet** [comment] 2018-09-20 16:10
@dauphine-dev 
Hi!
I followed your procedure, on Windows 7, FireFox 62.0 (64 bits).

- First problem: when I open the [subscription page](https://blogs.msdn.microsoft.com/visualstudio/feed/), Drop Feeds does not appear in the application list.
That may be a different problem.

- Then I go to the [ordinary page](https://blogs.msdn.microsoft.com/visualstudio), and let DF search the feeds.
- At that moment, there is nothing in the console.
- I select the main feed (Visual Studio Blog, the 3rd in the list).
- The problematic window shows.
- At this moment one error appears in the console:
`TypeError: undefined has no properties. subscribe.js:25:37`
- When I click on the source file link, the console shows additional info:
```
error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:311:1
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:399:21
Line: 311, column: 1 main.js:1638
```

I tried to disable all other extensions too. That makes no difference.
A fresh FireFox profile does not make difference either.

Does it help ?

**Comment by dauphine-dev** [comment] 2018-09-20 17:12
Hi @ChrisBertrandDotNet ,
TypeError: undefined has no properties. subscribe.js:25:37 that line can help, I will take a look.

But I am note sure the subscription procedure is clear (and if it is not, it means Drop Feeds need to be improve to make that clear) or it is me: I haven't understood what you have just described.
Then the procedure subscription :
 - Go to a web page with feeds (like https://blogs.msdn.microsoft.com/visualstudio)
 - on upper right click on the "go to subscription page" icon, and select the feed to subscribe.
![1-dropfeeds-subscribe](https://user-images.githubusercontent.com/36274213/45834479-8777db80-bd07-11e8-9dd9-6c1368bddf46.png)
 - then you get the subscription page
![2-dropfeeds-subscribe](https://user-images.githubusercontent.com/36274213/45834539-b2622f80-bd07-11e8-870e-565150399d9d.png)
 - on upper right click on the "subscribe now" icon, and click on the "Subscribe now"
![3-dropfeeds-subscribe](https://user-images.githubusercontent.com/36274213/45834615-e63d5500-bd07-11e8-9b66-bf884118df21.png)
 - then in the just opened subscription window select the target folder and click on the subscribe button
![4-dropfeeds-subscribe](https://user-images.githubusercontent.com/36274213/45834869-a4f97500-bd08-11e8-9a4d-f1083456bf93.png)
 - now the feed is available in Drop Feeds
![5-dropfeeds-subscribe](https://user-images.githubusercontent.com/36274213/45834883-b6428180-bd08-11e8-9393-ce247fdfab69.png)

Please tell me if the subscribe procedure is clear/intuitive, or if I need to improve Drop Feeds on this point (or may be add a help page some where)

**Comment by dauphine-dev** [comment] 2018-09-20 18:51
@ChrisBertrandDotNet 
I have take a look.
Can you open the Drop Feeds debug view

To get the debug view url :
 - on the sidebar collapse all folders and right click on the blank zone:

![drop-feeds1](https://user-images.githubusercontent.com/36274213/45839399-84371c80-bd14-11e8-958b-730e58b9fee8.png)

- and copy the url from "the Address" field

![drop-feeds2](https://user-images.githubusercontent.com/36274213/45839494-cceed580-bd14-11e8-88e3-86d46e22235e.png)

 - paste the url in firefox address bar, replace sidebar.html by debug.html and hit "enter"
 - look for "subscribeInfoWinId"
![drop-feeds3](https://user-images.githubusercontent.com/36274213/45839660-4b4b7780-bd15-11e8-928c-1a4d769612cb.png)

Can you look for the value of this field before your open the subscribe page (think to refresh the debug page),  and after you have opened subscribe page (think again to refresh the debug page) ?

Thank you.

Any way I will do a fix that it will provide to you a degraded mode that will allow you to subscribe, but you will to have to close the subscribe window manually.

Recently Fifefox has deny to webextensions to close windows, then I had to modify the way to close windows, but in you case it seems to not work. But please answer me to the question under, then I will can do a better fix.

Thank you.

**Comment by ChrisBertrandDotNet** [comment] 2018-09-24 16:34
@dauphine-dev 
Current state (on FireFox 62.0.2 and DF 0.8.5c)

There are many ways to add a RSS, isn't it ?
Currently, many of them do not work.

- There is no subscription button on the address bar: (maybe DF is not detected ?)
![no subscription button](https://user-images.githubusercontent.com/33118130/45964616-97086480-c026-11e8-96b0-e18b7de5eb79.png)


- If I open the general sub-menu, the subscription entry is disabled:
![subscription menu is disabled](https://user-images.githubusercontent.com/33118130/45964333-d2eefa00-c025-11e8-87aa-a3222fc41809.png)

- If I open the RSS page directly (https://blogs.msdn.microsoft.com/visualstudio/feed/), DF is not listed in this menu:
![df not listed in the menu on direct feed page](https://user-images.githubusercontent.com/33118130/45964433-10538780-c026-11e8-9e87-03427dfb2bd1.png)

- If I open the RSS page directly (https://blogs.msdn.microsoft.com/visualstudio/feed/), this time the subscription button appears and DF is listed: (good)
![df listed in the button on direct feed page](https://user-images.githubusercontent.com/33118130/45964909-50673a00-c027-11e8-9e30-ef60c67bdef0.png)

- If I display DF then click on the magnifying glass icon, the RSS channel choice is ok:
![channel choice is ok](https://user-images.githubusercontent.com/33118130/45964834-1d24ab00-c027-11e8-99d5-a0550f111d95.png)

- The UI is now filled: (that is new, it was empty one week ago)
![now the rss feed appears](https://user-images.githubusercontent.com/33118130/45964979-7e4c7e80-c027-11e8-9ee0-54e232856392.png)

- I can add the RSS, but that does not close the window (maybe a defect in FireFox).

- Unfortunately, DF can't open the feeds it lists:
![df can t open its feeds](https://user-images.githubusercontent.com/33118130/45964856-2f9ee480-c027-11e8-83bb-5d568d78df2e.png)

**Comment by ChrisBertrandDotNet** [comment] 2018-09-24 16:45
@dauphine-dev 

[tested on Windows 10]
Sorry, no subscribeInfoWinId item at any moment (I refreshed the debug window at every step).

![no subscribeinfowinid](https://user-images.githubusercontent.com/33118130/45965866-e8662300-c029-11e8-8c67-81e3c13ca30f.png)

**Comment by dauphine-dev** [comment] 2018-09-26 11:17
> I can add the RSS, but that does not close the window (maybe a defect in FireFox).

Yes it what I have called the degraded mode.


> Unfortunately, DF can't open the feeds it lists:

This is another issue.

Please can you right-click on "The visual studio Blog" in the feed list and then click on "Info" and put here a screen capture ?

**Comment by dauphine-dev** [comment] 2018-09-26 11:32
I have added some debug info in this private version 
https://send.firefox.com/download/e39d12d8a7/#TtxZRvOoxwO_GzE1hVXc7A

Please can you install it and redo same as https://github.com/dauphine-dev/drop-feeds/issues/57#issuecomment-421553947

Thank you

@thieleke : I know that you use Drop Feeds on Windows, do have the same issue ?

**Comment by dauphine-dev** [comment] 2018-10-16 09:09
I have can tested on Windows 7 x64, and Windows 10 x64.  And it works for me. I think there in some thing specifics to your computers.

The link upper has expire then I have upload again  the private version with debug info
https://we.tl/t-Bkk3FuQcbj

Please can you install it and redo same as #57 (comment)

If I get no news in the next weeks, and I can not reproduce then I will close this issue.

Thank you

**Comment by dauphine-dev** [comment] 2018-11-26 14:07
I can still not reproduce, then I close this issue.

If it is needed don't hesitate to open it again, thank you.

**Closed by dauphine-dev** 2018-11-26 14:07 UTC
Labels: bug
